nodeLinker: node-modules

# Specify exact versions for dependencies
defaultSemverRangePrefix: ''

# Prevent most cases of installing compromised packages
npmMinimalAgeGate: '7d'

# Postinstall scripts in node_modules should be enabled thoughtfully
enableScripts: false
